# binarna = input("Podaj liczbę w systemie binarnym: ")
# liczba1 = int(binarna, 2)
# print("Liczba w systemie dziesiętnym: ",liczba1)

binarna = input("Podaj liczbę w systemie binarnym: ")
pierwsza = int(binarna[0])
druga = int(binarna[1])
trzecia = int(binarna[2])
czwarta = int(binarna[3])
piata = int(binarna[4])
szosta = int(binarna[5])
dziesietna = (pierwsza * 32) + (druga * 16) + (trzecia * 8) + (czwarta * 4) + (piata * 2) + (szosta * 1)
print("Liczba w systemie dziesiętnym: ",dziesietna)